version: "3"

services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - /home/juancarlos/mongodb/database:/data/db
    ports:
    - 27018:27017
    restart: unless-stopped

  backend:
    image: backend:local
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: npm run dev
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - "./backend:/app"
    ports:
      - "3000"
    restart: unless-stopped